source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'thin'
gem 'slim-rails'
gem 'foundation-rails'
gem 'owlcarousel-rails'
gem 'mixitup_rails'
gem 'bxslider-rails'
gem 'rails-admin-scaffold'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-vkontakte'
gem 'simple_form'
gem 'simple_form_fancy_uploads'
gem 'paperclip'
gem 'paperclip-compression'
gem 'protected_attributes'
gem 'ckeditor'
gem 'breadcrumbs_on_rails'
gem 'russian'
gem 'seed_dump'
gem 'activerecord-reset-pk-sequence'
gem 'truncate_html'
gem 'mailchimp-api', require: 'mailchimp'
gem 'parallax-rails'
gem 'google-analytics-rails'
gem 'disqus'
gem 'letter_opener', group: :development

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end
