source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', ' 2.7.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'thin'
gem 'slim-rails'
gem 'foundation-rails', '5.5.1.0'
gem 'owlcarousel-rails'
gem 'mixitup_rails'
gem 'bxslider-rails', '4.1.0'
gem 'rails-admin-scaffold'
gem 'devise', '3.4.1'
gem 'omniauth'
gem 'omniauth-facebook', '2.0.0'
gem 'omniauth-vkontakte'
gem 'simple_form'
gem 'simple_form_fancy_uploads'
gem 'paperclip', '4.2.1'
gem 'paperclip-compression', '0.3.6'
gem 'protected_attributes', '1.0.8'
gem 'ckeditor', '4.1.1'
gem 'breadcrumbs_on_rails', '2.3.0'
gem 'russian'
gem 'seed_dump'
gem 'activerecord-reset-pk-sequence', '0.2.0'
gem 'truncate_html'
gem 'mailchimp-api', require: 'mailchimp'
gem 'parallax-rails'
gem 'google-analytics-rails'
gem 'disqus'
gem 'letter_opener', group: :development

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end
